apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: approval-with-parameters
on:
  workflow_dispatch:
jobs:
  use-approval-parameters:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Echo parameters
        shell: sh
        run: |
          echo "${{ fromJSON(outputs.approvalInputValues).In1 }}"
          echo "${{ fromJSON(outputs.approvalInputValues).In2 }}"
    needs:
      - User-input
  User-input:
    with:
      approvers: 9e6cef82-03d3-11eb-9d67-42010a83ae35
      disallowLaunchByUser: false
      instructions: Please provide inputs
      approvalInputs: |
        In1:
          type: string
        In2:
          type: number
          default: 121
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml
