apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: approval-input-drive-workflow
on:
  workflow_dispatch:
jobs:
  User-input:
    with:
      approvers: 9e6cef82-03d3-11eb-9d67-42010a83ae35,3b95fb7e-e80d-11ea-a794-42010a83ae1a
      disallowLaunchByUser: false
      instructions: Please provide inputs
      approvalInputs: |
        run-additional-tests:
          type: boolean
          default: false
          description: Run automated tests only if needed
        manual-test-results:
          type: number
          required: true
          description: Manual test passing percentage
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/.cloudbees/testing/custom-job.yml
  run-tests:
    needs: User-input
    #if: "${{ fromJSON(needs.User-input.outputs.approvalInputValues).run-additional-tests}}"
    #if: fromJSON(needs.User-input.outputs.approvalInputValues).run-additional-tests
    #if: "false"
    if: fromJSON(needs.User-input.outputs.approvalInputValues).run-additional-tests == "true"
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Tests
        shell: sh
        run: echo "Running tests"
  publish-test-results:
    needs: User-input
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Echo conditional
        shell: sh
        run: echo "${{ fromJSON(needs.User-input.outputs.approvalInputValues).run-additional-tests}}"
      - uses: cloudbees-io/publish-evidence-item@v1
        name: Publish test results
        with:
          content: |
            ## Manual Test results
            # ${{ fromJSON(needs.User-input.outputs.approvalInputValues).manual-test-results }} %