apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Approval
on:
  workflow_dispatch:
    inputs:
      instructions:
        type: string
        default: Approve me (parameter)!
jobs:
  planning:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo Planning
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    needs: [Prebuild,planning]
  Prebuild:
    needs: planning
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 3b95fb7e-e80d-11ea-a794-42010a83ae1a,a90827d8-9e26-11ec-a591-42010a83ae5a
      disallowLaunchByUser: false
      instructions: ${{ inputs.instructions }}
