apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Approval - no approvers
on:
  workflow_dispatch:
    inputs:
      instructions:
        type: string
        default: Approve me (parameter)!
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    needs:
      - Prebuild
  Prebuild:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/.cloudbees/testing/custom-job.yml@CBP-7212-notifyEligibleUsers
    with:
      #approvers: ""
      disallowLaunchByUser: false
      notifyAllEligibleUsers: true
      instructions: ${{ inputs.instructions }}
      debug: true
