apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Approval
on:
  workflow_dispatch:
    inputs:
      instructions:
        type: string
        default: Parameter default
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    needs:
      - Prebuild
  Prebuild:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 9e6cef82-03d3-11eb-9d67-42010a83ae35,4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      disallowLaunchByUser: false
      instruction: ${{ inputs.instructions }}
